### ISSUE TITLE
Fix README documentation

### ISSUE THREAD

**Issue by ionpetro** [FirixQ/language-sigma16#1]
Hello, 

I would like to contribute to your project by updating the README file. I think this package is very useful, but a user that visits your repository cannot understand what it does if he doesn't read the src code.

**Comment by MHCooke** [comment]
I think the README is very clear. This package adds syntax highlighting for Sigma16 for Atom. That is what the README says and that is what the package does.

Out of interest, why do you think this package is very useful?
